---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-cluster-master
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch
  annotations:
    majorVersion: "2"
spec:
  template:
    metadata:
      name: "opensearch-cluster-master"
      labels:
        app.kubernetes.io/name: opensearch
        app.kubernetes.io/instance: opensearch
    spec:
      containers:
      - name: "opensearch"
        resources:
          limits:
            cpu: 2000m
            memory: 4G
          requests:
            cpu: 1000m
            memory: 2G
      - name: exporter
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi