resources:

  # Monitoring
  - ../../vendor/katalog/monitoring/prometheus-operator
  - ../../vendor/katalog/monitoring/prometheus-operated
  - ../../vendor/katalog/monitoring/grafana
  - ../../vendor/katalog/monitoring/goldpinger
  - ../../vendor/katalog/monitoring/kube-state-metrics
  - ../../vendor/katalog/monitoring/node-exporter
  - ../../vendor/katalog/monitoring/alertmanager-operated

patchesStrategicMerge:

  - patches/alertmanager-operated-replicas.yml
  - patches/alertmanager-operated-resources.yml
  - patches/prometheus-operated-resources.yml
  - patches/prometheus-operator-resources.yml
  - patches/grafana-resources.yml
