---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  # Logging
  - ../../vendor/katalog/logging/opensearch-single
  - ../../vendor/katalog/logging/cerebro
  # - ../../vendor/katalog/logging/curator
  - ../../vendor/katalog/logging/opensearch-dashboards
  - ../../vendor/katalog/logging/logging-operated
  - ../../vendor/katalog/logging/logging-operator
  - ../../vendor/katalog/logging/configs
  - ../../vendor/katalog/logging/minio-ha


patchesStrategicMerge:
  - patches/kibana-resources.yml
  - patches/elasticsearch-resources.yml
  # - patches/fluentd-resources.yml
  # - patches/fluentbit-resources.yml


