---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: random-logger

resources: 
  - random-log-output.yml
  - ramdom-log-flow.yml


generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: random-log-index-template
    files:
      - random-log-index-template=random-log-index-template.json

